version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: PR_backend
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - laravel_net
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=pr_searching
      - DB_USERNAME=pr_user
      - DB_PASSWORD=password

  db:
    image: mysql:8.2
    container_name: pr_searching
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: pr_searching
      MYSQL_USER: pr_user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: PR_frontend
    networks:
      - laravel_net

  nginx:
    image: nginx:latest
    container_name: PR_nginx
    ports:
      - "80:80"
    volumes:
       - ./nginx.conf:/etc/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - laravel_net

volumes:
  db_data:

networks:
  laravel_net:

